### ISSUE TITLE
What does it do

### ISSUE THREAD

**Issue by Soneji** [wdhg/voxels#1]
![image](https://user-images.githubusercontent.com/12625848/104860006-179ead80-5921-11eb-96c4-2a61fe222c02.png)

All i see is a maze and my cpu fan go whirr

**Comment by wdhg** [comment]
working as intended

**Comment by wdhg** [comment]
pc fan go brr

**Comment by Soneji** [comment]
pls provide more infos on what is supposed to be

**Comment by wdhg** [comment]
I'm just playing around with voxels. there isn't really and end goal
